spring:
  profiles: dev
#  activemq:
#    broker-url:

#  datasource:
#    url: jdbc:mysql://192.168.0.50:3307/cc-dms-zac2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
#    userName: root
#    password:
#    druid:
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      test-on-borrow: true

  datasource:
    url: jdbc:mysql://localhost:3306/cc_dapp_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: rt@FLH301

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

custom:

