spring:
  profiles:
    active: dev

  jackson:
    time-zone: GMT+8

#  cache:
#    type: ehcache
#    ehcache:
#      config: classpath:/ehcache.xml

#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp

#mybatis:
#  type-aliases-package: com.cc.dapp.domain
#  mapper-locations: classpath:mapper/*.xml

info:
  api-doc: /swagger-ui.html

#logging:
#  config: classpath:logback-spring.xml