spring:
  profiles:
    active: dev

  jackson:
    time-zone: GMT+8

  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml

info:
  api-doc: /swagger-ui.html

logging:
  config: classpath:logback-spring.xml